---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: insta-deploy
   labels:
     app: instagram
     env: sbox
spec:
  selector:
    matchLabels:
      app: instagram
  replicas: 3
  template:
    metadata:
       name: insta-deploy
       labels:
         app: instagram
         env: sbox
         version: v1-VC
    spec:
     containers:
      - name: insta-deploy-cont
        image: navyadevopsaws25/batch17drepo:pythonimg
        ports:
          - containerPort: 80
